jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users: []

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            http_basic: ~
