spy_timeline:

    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                timeline:  Spy\DemoBundle\Entity\Timeline
                action:    Spy\DemoBundle\Entity\Action
                component: Spy\DemoBundle\Entity\Component
                action_component: Spy\DemoBundle\Entity\ActionComponent

    notifiers:
        - spy_timeline.unread_notifications

    filters:
        duplicate_key:
            priority: 10
        data_hydrator:
            priority: 20
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm
    spread:
        on_subject: true          # Spread each action on subject too
        on_global_context: true   # Spread automatically on global context
        deployer: spy_timeline.spread.deployer.default
        delivery: immediate
