spy_timeline:

    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                timeline:  Acme\TimelineBundle\Entity\Timeline
                action:    Acme\TimelineBundle\Entity\Action
                component: Acme\TimelineBundle\Entity\Component
                action_component: Acme\TimelineBundle\Entity\ActionComponent
        #odm:
        #    object_manager: doctrine.odm.entity_manager
        #redis:
        #    client: snc_redis.default

    notifiers: []
        #- spy_timeline.unread_notifications

    filters:
        duplicate_key:
            priority: 10
        data_hydrator:
            priority: 20
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine

    spread:
        on_subject: true          # Spread each action on subject too
        on_global_context: true   # Spread automatically on global context
        deployer: spy_timeline.spread.deployer.default
        delivery: immediate

    #render:
    #    path: toto
