spy_timeline:
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                timeline:         Acme\DemoBundle\Entity\Timeline
                action:           Acme\DemoBundle\Entity\Action
                component:        Acme\DemoBundle\Entity\Component
                action_component: Acme\DemoBundle\Entity\ActionComponent

    notifiers:
        - spy_timeline.unread_notifications

    filters:
        duplicate_key:
            priority: 10
        data_hydrator:
            priority: 20
            filter_unresolved: false
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm
    spread:
        on_subject: false         # DEFAULT IS TRUE  Spread each action on subject too
        on_global_context: true   # Spread automatically on global context
        deployer: spy_timeline.spread.deployer.default
        delivery: immediate
    render:
        path:     'AcmeDemoBundle:Timeline/verbs'
        resources:
            - 'AcmeDemoBundle:Timeline:components.html.twig'
